version: '2'
services:
  #elasticsearch:
  #  image: elasticsearch
  #  ports: ["9200:9200"]
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/youdo
    ports:
      - "3000:3000"
    depends_on:
      - db
