default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV['DATABASE_DEVELOPMENT_HOST'] %>
  port: <%= ENV['DATABASE_DEVELOPMENT_PORT'].to_i %>
  username: <%= ENV['DATABASE_DEVELOPMENT_USERNAME'] %>
  password: <%= ENV['DATABASE_DEVELOPMENT_PASSWORD'] %>
  database: <%= ENV['DATABASE_DEVELOPMENT_NAME'] %>

test:
  <<: *default
  host: <%= ENV['DATABASE_TEST_HOST'] %>
  port: <%= ENV['DATABASE_TEST_PORT'].to_i %>
  username: <%= ENV['DATABASE_TEST_USERNAME'] %>
  password: <%= ENV['DATABASE_TEST_PASSWORD'] %>
  database: <%= ENV['DATABASE_TEST_NAME'] %>

production:
  <<: *default
  host: <%= ENV['DATABASE_PRODUCTION_HOST'] %>
  port: <%= ENV['DATABASE_PRODUCTION_PORT'].to_i %>
  username: <%= ENV['DATABASE_PRODUCTION_USERNAME'] %>
  password: <%= ENV['DATABASE_PRODUCTION_PASSWORD'] %>
  database: <%= ENV['DATABASE_PRODUCTION_NAME'] %>
