default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: admin
  password: admin
  host: 192.168.101.118
  port: 5432

development:
  <<: *default
  database: youdo_development

test:
  <<: *default
  database: youdo_test


production:
  <<: *default
  database: youdo_production
  username: youdo
  password: <%= ENV['YOUDO_DATABASE_PASSWORD'] %>
