DATABASE_DEVELOPMENT_NAME: 'youdo_development'
DATABASE_DEVELOPMENT_HOST: '192.168.101.118'
DATABASE_DEVELOPMENT_PORT: '5432'
DATABASE_DEVELOPMENT_USERNAME: 'admin'
DATABASE_DEVELOPMENT_PASSWORD: 'admin'

DATABASE_TEST_NAME: 'youdo_test'
DATABASE_TEST_HOST: '192.168.101.118'
DATABASE_TEST_PORT: '5432'
DATABASE_TEST_USERNAME: 'admin'
DATABASE_TEST_PASSWORD: 'admin'

DATABASE_PRODUCTION_NAME: 'youdo_production'
DATABASE_PRODUCTION_HOST: 'mudasdbinstance.csljkcxe7kdr.us-east-1.rds.amazonaws.com'
DATABASE_PRODUCTION_PORT: '5432'
DATABASE_PRODUCTION_USERNAME: 'mudas'
DATABASE_PRODUCTION_PASSWORD: 'mudas-prod'

SECRET_KEY_BASE: ''
ELASTICSEARCH_URL: "http://172.24.0.1:9200"